### PR TITLE
Servo mode support

### PR DESCRIPTION
**Pull request by edvinerikson**
- servo mode support
- fixed "handle changing read handlers" test

### CODE REVIEW

**Comment by iamdustan** [comment]
Could you add/update the Servo example for this as well? Have you had the opportunity to test it with hardware?

**Comment by edvinerikson** [comment]
Absolutely, I will add an example! Unfortunately I don't have any servo to test it with.

**Comment by iamdustan** [comment]
Cool. I'll test this with a couple of my servos and get familiar with the target API. 

It looks like the config object is just `{min: number, max: number}`. Would it be with decomposing that directly to the props on the outside API?

**Comment by edvinerikson** [comment]
My idea is that the `config` prop will be used for both i2c and servo and then switch what types it accepts based on pin mode (in flowtype). I also think that we should add a `<Servo />` component that can accept min/max as props (will add it when I add the example if you think it is good idea).

**Comment by iamdustan** [comment]
My thoughts have distilled down to the two initial thoughts/questions.

* I’m not sure if we want to expose the `config` prop directly yet. I’m still pretty naive on it, but I think we may actually want to have fine-grained control of calls to the `*Config` firmata methods.
* Although we have the generic `type` which includes `SERVO` as an option, does it make sense to introduce a `<servo />` generic component for this??

**Comment by edvinerikson** [comment]
> I’m not sure if we want to expose the config prop directly yet. I’m still pretty naive on it, but I think we may actually want to have fine-grained control of calls to the *Config firmata methods.

Maybe we should expose more methods on the HardwareManager to control this better? 
We should probably split the config into `servoConfig` and `i2cConfig` (remove the abstraction). 



> Although we have the generic type which includes SERVO as an option, does it make sense to introduce a <servo /> generic component for this??

It seems a little bit odd to me because everything is a `pin` and expose a generic `servo` component doesn't make sense to me because they will really just do the same thing. Maybe it make more sense if we remove the `pin` component and expose `HardwareManager` in the public api instead? I  like the idea of a composite `<Servo />` component which uses the lower level `<pin />` api. 

If we expose more fine grained controls from the `HardwareManager` maybe we can keep the `<pin />` and add a generic `<servo />` component. They will both use the same api except that the `<servo />` will always have `mode="SERVO"`. However you can still use the `<pin />` to configure a servo except that it is more convenient to use the `<servo />` component.
```
<servo pin={1} min={20} max={90} value={30} />

<pin pin={1} servoConfig={{min: 20, max: 90}} mode="SERVO" value={30} />
```


I am not sure what the best way is to do this. I like the declarative api but if the abstraction doesn't make sense I think it will be hard to use it. There are a lot of ideas here but I am not sure if any of them are good though.

**Comment by iamdustan** [comment]
Eventually HardwareManager will likely be exposed in some way. The new work on the react reconciler may require more constraints on this. In the meantime I think it’s pretty premature to still think about exposing it. The hoops we jump through on the internals (which really aren’t many yet) don’t matter that much if the public API is clean.

I would say that any of the following are acceptable:

```
<servo pin={1} min={20} max={90} value={30} />
<Servo pin={1} min={20} max={90} value={30} />
<pin mode="SERVO" pin={1} min={20} max={90} value={30} />
```

Exposing the `config` object still seems too low level and required the consumer to know more about firmata than they necessarily need to.

---

> everything is a pin

Depending on the definition yes. In DOM everything extends Node, but doesn’t mean that `div`s and `span`s don’t have their place. `<pin />` ~== `Node` in this situation. It’s the most flexible and least opinionated while the higher level abstractions are explored. Personally I don’t think it matters between `<servo />` or `<Servo />` being the initial way to do this, but I do feel strongly that exposing either the `servoConfig` method or the accompanying `config` object is too low.

---

There are a few other things to fill in with this as well.

What is the representation of a `ref` node? IMO it shouldn’t be the default firmata binding, but something representative of that exact pin.

```jsx
let pin13;
<pin ref={node => pin13 = node} pin={13} />
```

where `pin13` will be something like the following:

```
{
  value (getter/setter),
  mode (getter/setter),
  addEventListener() => {},
  removeEventListener() => {},
}
```

At this level we may add hooks for direct HardwareManager calls (once again taking inspiration from RN), but once again that should be constrained and deferred until it is absolutely necessary.

Adding APIs is easier than removing them so keep the surface area small :)

**Comment by edvinerikson** [comment]
Sorry for my late response on the PR.. 
> I would say that any of the following are acceptable:
 ```
<servo pin={1} min={20} max={90} value={30} />
<Servo pin={1} min={20} max={90} value={30} />
<pin mode="SERVO" pin={1} min={20} max={90} value={30} />
```

I would say that `<pin mode="SERVO" pin={1} min={20} max={90} value={30} />` should be `<pin mode="SERVO" pin={1} servoConfig={{ min:20, max: 90 }} value={30} />` instead if want to export the min/max settings on the pin.


> Exposing the config object still seems too low level and required the consumer to know more about firmata than they necessarily need to.

I'm thinking that the `pin` component is low-level and that consumers shouldn't have to use it if they don't want to build something new that we don't already support. 


> Depending on the definition yes. In DOM everything extends Node, but doesn’t mean that divs and spans don’t have their place. <pin /> ~== Node in this situation. It’s the most flexible and least opinionated while the higher level abstractions are explored. Personally I don’t think it matters between <servo /> or <Servo /> being the initial way to do this, but I do feel strongly that exposing either the servoConfig method or the accompanying config object is too low.

I also think that exposing servoConfig/i2cConfig on the pin is "weird" (even if I suggested it above..) and that's also why I suggested that we somehow export the Hardware Manager so that we can call it directly from there. If we do that we can have a `<servo />/<Servo />` component which calls that function.

Having a ref node to the component would be really nice and I'm 100% to support that, then we can have the servoConfig there. However I like to have a declarative API to control settings/values/etc.

**Pull request closed without merging**
